name: Update thailand

on:
  schedule:
    - cron: '45 */6 * * *'
  workflow_dispatch:     # 允許手動觸發

jobs:
  update-forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy>=2 openmeteo_requests retry_requests requests_cache scikit-learn>=1.6

      - name: Update Forecast Data
        run: |
          python 2_predict_thailand.py update_thailand --forecast_days 16 --batch_size 40
          python 2_predict_thailand.py forecast_thailand

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update forecast data [skip ci] $(date)"
          git push
